import p1_img from "./product_1.png";
import p2_img from "./product_2.png";
import p3_img from "./product_3.png";
import p4_img from "./product_4.png";
import p5_img from "./product_5.png";
import p6_img from "./product_6.png";
import p7_img from "./product_7.png";
import p8_img from "./product_8.png";
import p9_img from "./product_9.png";
import p10_img from "./product_10.png";
import p11_img from "./product_11.png";
import p12_img from "./product_12.png";
import p13_img from "./product_13.png";
import p14_img from "./product_14.png";
import p15_img from "./product_15.png";
import p16_img from "./product_16.png";
import p17_img from "./product_17.png";
import p18_img from "./product_18.png";
import p19_img from "./product_19.png";
import p20_img from "./product_20.png";
import p21_img from "./product_21.png";
import p22_img from "./product_22.png";
import p23_img from "./product_23.png";
import p24_img from "./product_24.png";
import p25_img from "./product_25.png";
import p26_img from "./product_26.png";
import p27_img from "./product_27.png";
import p28_img from "./product_28.png";
import p29_img from "./product_29.png";
import p30_img from "./product_30.png";
import p31_img from "./product_31.png";
import p32_img from "./product_32.png";
import p33_img from "./product_33.png";
import p34_img from "./product_34.png";
import p35_img from "./product_35.png";
import p36_img from "./product_36.png";

const all_products = [
  {
    id: 1,
    name: "Colchão King Size Premium",
    desc: "Colchão confortável com molas ensacadas.",
    category: 1,
    category_name: "Colchões",
    rating: 5,
    quant: 1,
    quantvend: 25,
    unit: "un",
    image: p1_img,
    price: 1200,
    parc: true,
    parc_quant: 12,
    price_unit: 1200,
    free_shipping: true,
    offer: true,
    porc_offer: 15,
    offer_price: 1020,
    old_price: 1200,
  },
  {
    id: 2,
    name: "Beliche Madeira Maciça",
    desc: "Beliche robusto com estrutura de madeira.",
    category: 2,
    category_name: "Beliches",
    rating: 5,
    quant: 1,
    quantvend: 12,
    unit: "un",
    image: p2_img,
    price: 850,
    parc: true,
    parc_quant: 10,
    price_unit: 850,
    free_shipping: false,
    offer: true,
    porc_offer: 10,
    offer_price: 765,
    old_price: 850,
  },
  {
    id: 3,
    name: "Colchão Ortopédico Solteiro",
    desc: "Ideal para quem busca conforto e saúde.",
    category: 1,
    category_name: "Colchões",
    rating: 4,
    quant: 1,
    quantvend: 8,
    unit: "un",
    image: p3_img,
    price: 450,
    parc: true,
    parc_quant: 6,
    price_unit: 450,
    free_shipping: false,
    offer: false,
    porc_offer: 0,
    offer_price: 0,
    old_price: 450,
  },
  {
    id: 4,
    name: "Beliche com Gavetas Embutidas",
    desc: "Beliche com amplo espaço de armazenamento.",
    category: 2,
    category_name: "Beliches",
    rating: 4,
    quant: 1,
    quantvend: 15,
    unit: "un",
    image: p4_img,
    price: 1100,
    parc: true,
    parc_quant: 12,
    price_unit: 1100,
    free_shipping: true,
    offer: true,
    porc_offer: 20,
    offer_price: 880,
    old_price: 1100,
  },
  {
    id: 5,
    name: "Colchão de Espuma D45 Casal",
    desc: "Espuma de alta densidade para suporte extra.",
    category: 1,
    category_name: "Colchões",
    rating: 3,
    quant_rating: 2,
    quant: 1,
    quantvend: 18,
    unit: "un",
    image: p5_img,
    price: 650,
    parc: true,
    parc_quant: 8,
    price_unit: 650,
    free_shipping: true,
    offer: false,
    porc_offer: 0,
    offer_price: 0,
    old_price: 650,
  },
  {
    id: 6,
    name: "Beliche Metálica Moderna",
    desc: "Design moderno com estrutura metálica resistente.",
    category: 2,
    category_name: "Beliches",
    rating: 5,
    quant: 1,
    quantvend: 10,
    unit: "un",
    image: p6_img,
    price: 950,
    parc: true,
    parc_quant: 12,
    price_unit: 950,
    free_shipping: false,
    offer: true,
    porc_offer: 10,
    offer_price: 855,
    old_price: 950,
  },
  {
    id: 7,
    name: "Colchão Inflável Queen",
    desc: "Colchão prático para viagens e eventos.",
    category: 1,
    category_name: "Colchões",
    rating: 4,
    quant: 1,
    quantvend: 30,
    unit: "un",
    image: p7_img,
    price: 200,
    parc: false,
    parc_quant: 0,
    price_unit: 200,
    free_shipping: true,
    offer: true,
    porc_offer: 5,
    offer_price: 190,
    old_price: 200,
  },
  {
    id: 8,
    name: "Beliche Compacta para Apartamentos",
    desc: "Beliche com design compacto para pequenos espaços.",
    category: 2,
    category_name: "Beliches",
    rating: 4,
    quant: 1,
    quantvend: 20,
    unit: "un",
    image: p8_img,
    price: 780,
    parc: true,
    parc_quant: 10,
    price_unit: 780,
    free_shipping: true,
    offer: false,
    porc_offer: 0,
    offer_price: 0,
    old_price: 780,
  },
  {
    id: 9,
    name: "Colchão Solteiro Kids",
    desc: "Ideal para crianças, com proteção anti-ácaro.",
    category: 1,
    category_name: "Colchões",
    rating: 5,
    quant: 1,
    quantvend: 22,
    unit: "un",
    image: p9_img,
    price: 300,
    parc: true,
    parc_quant: 6,
    price_unit: 300,
    free_shipping: false,
    offer: true,
    porc_offer: 15,
    offer_price: 255,
    old_price: 300,
  },
  {
    id: 10,
    name: "Beliche com Cortinas para Privacidade",
    desc: "Beliche com cortinas integradas para privacidade.",
    category: 2,
    category_name: "Beliches",
    rating: 5,
    quant: 1,
    quantvend: 9,
    unit: "un",
    image: p10_img,
    price: 1150,
    parc: true,
    parc_quant: 12,
    price_unit: 1150,
    free_shipping: true,
    offer: true,
    porc_offer: 25,
    offer_price: 862.5,
    old_price: 1150,
  },
  {
    id: 11,
    name: "Colchão Ortopédico Queen",
    desc: "Colchão de alta densidade para suporte da coluna.",
    category: 1,
    category_name: "Colchões",
    rating: 4,
    quant: 1,
    quantvend: 14,
    unit: "un",
    image: p11_img,
    price: 750,
    parc: true,
    parc_quant: 8,
    price_unit: 750,
    free_shipping: false,
    offer: true,
    porc_offer: 10,
    offer_price: 675,
    old_price: 750,
  },
  {
    id: 12,
    name: "Beliche Infantil Colorido",
    desc: "Beliche divertido e colorido para crianças.",
    category: 2,
    category_name: "Beliches",
    rating: 5,
    quant: 1,
    quantvend: 5,
    unit: "un",
    image: p12_img,
    price: 950,
    parc: true,
    parc_quant: 10,
    price_unit: 950,
    free_shipping: true,
    offer: false,
    porc_offer: 0,
    offer_price: 0,
    old_price: 950,
  },
  {
    id: 13,
    name: "Colchão Espuma Viscoelástica Casal",
    desc: "Colchão que se ajusta ao formato do corpo.",
    category: 1,
    category_name: "Colchões",
    rating: 4,
    quant: 1,
    quantvend: 12,
    unit: "un",
    image: p13_img,
    price: 1200,
    parc: true,
    parc_quant: 12,
    price_unit: 1200,
    free_shipping: true,
    offer: true,
    porc_offer: 15,
    offer_price: 1020,
    old_price: 1200,
  },
  {
    id: 14,
    name: "Beliche com Escrivaninha",
    desc: "Beliche com espaço de estudo integrado.",
    category: 2,
    category_name: "Beliches",
    rating: 5,
    quant: 1,
    quantvend: 20,
    unit: "un",
    image: p14_img,
    price: 1300,
    parc: true,
    parc_quant: 12,
    price_unit: 1300,
    free_shipping: false,
    offer: true,
    porc_offer: 20,
    offer_price: 1040,
    old_price: 1300,
  },
  {
    id: 15,
    name: "Colchão Solteiro com Pillow Top",
    desc: "Extra conforto com pillow top macio.",
    category: 1,
    category_name: "Colchões",
    rating: 3,
    quant: 1,
    quantvend: 18,
    unit: "un",
    image: p15_img,
    price: 550,
    parc: true,
    parc_quant: 6,
    price_unit: 550,
    free_shipping: true,
    offer: false,
    porc_offer: 0,
    offer_price: 0,
    old_price: 550,
  },
  {
    id: 16,
    name: "Beliche com Escada Lateral",
    desc: "Design moderno com escada lateral para facilitar o acesso.",
    category: 2,
    category_name: "Beliches",
    rating: 4,
    quant: 1,
    quantvend: 16,
    unit: "un",
    image: p16_img,
    price: 1050,
    parc: true,
    parc_quant: 12,
    price_unit: 1050,
    free_shipping: true,
    offer: true,
    porc_offer: 15,
    offer_price: 892.5,
    old_price: 1050,
  },
  {
    id: 17,
    name: "Colchão Casal com Resfriamento",
    desc: "Tecnologia de resfriamento para um sono confortável.",
    category: 1,
    category_name: "Colchões",
    rating: 5,
    quant: 1,
    quantvend: 25,
    unit: "un",
    image: p17_img,
    price: 1300,
    parc: true,
    parc_quant: 12,
    price_unit: 1300,
    free_shipping: false,
    offer: true,
    porc_offer: 10,
    offer_price: 1170,
    old_price: 1300,
  },
  {
    id: 18,
    name: "Beliche com Colchões Inclusos",
    desc: "Beliche completo com dois colchões de espuma.",
    category: 2,
    category_name: "Beliches",
    rating: 4,
    quant: 1,
    quantvend: 10,
    unit: "un",
    image: p18_img,
    price: 1450,
    parc: true,
    parc_quant: 12,
    price_unit: 1450,
    free_shipping: true,
    offer: false,
    porc_offer: 0,
    offer_price: 0,
    old_price: 1450,
  },
  {
    id: 19,
    name: "Colchão Infantil com Estampa Divertida",
    desc: "Colchão com estampa divertida e conforto para crianças.",
    category: 1,
    category_name: "Colchões",
    rating: 4,
    quant: 1,
    quantvend: 7,
    unit: "un",
    image: p19_img,
    price: 400,
    parc: true,
    parc_quant: 6,
    price_unit: 400,
    free_shipping: false,
    offer: true,
    porc_offer: 10,
    offer_price: 360,
    old_price: 400,
  },
  {
    id: 20,
    name: "Beliche de Metal Reforçado",
    desc: "Beliche robusto com estrutura metálica resistente.",
    category: 2,
    category_name: "Beliches",
    rating: 5,
    quant: 1,
    quantvend: 9,
    unit: "un",
    image: p20_img,
    price: 900,
    parc: true,
    parc_quant: 10,
    price_unit: 900,
    free_shipping: true,
    offer: true,
    porc_offer: 10,
    offer_price: 810,
    old_price: 900,
  },
  {
    id: 21,
    name: "Colchão Queen com Alta Elasticidade",
    desc: "Colchão que proporciona suporte e conforto ideal.",
    category: 1,
    category_name: "Colchões",
    rating: 5,
    quant: 1,
    quantvend: 22,
    unit: "un",
    image: p21_img,
    price: 1100,
    parc: true,
    parc_quant: 12,
    price_unit: 1100,
    free_shipping: false,
    offer: false,
    porc_offer: 0,
    offer_price: 0,
    old_price: 1100,
  },
  {
    id: 22,
    name: "Beliche com Cabideiro Integrado",
    desc: "Beliche com cabideiro para melhor organização.",
    category: 2,
    category_name: "Beliches",
    rating: 4,
    quant: 1,
    quantvend: 12,
    unit: "un",
    image: p22_img,
    price: 1250,
    parc: true,
    parc_quant: 12,
    price_unit: 1250,
    free_shipping: true,
    offer: true,
    porc_offer: 20,
    offer_price: 1000,
    old_price: 1250,
  },
  {
    id: 23,
    name: "Colchão Solteiro Premium com Molas",
    desc: "Conforto com molas ensacadas para um sono perfeito.",
    category: 1,
    category_name: "Colchões",
    rating: 5,
    quant: 1,
    quantvend: 17,
    unit: "un",
    image: p23_img,
    price: 850,
    parc: true,
    parc_quant: 10,
    price_unit: 850,
    free_shipping: true,
    offer: true,
    porc_offer: 10,
    offer_price: 765,
    old_price: 850,
  },
  {
    id: 24,
    name: "Beliche com Armário Embutido",
    desc: "Beliche multifuncional com armário integrado.",
    category: 2,
    category_name: "Beliches",
    rating: 4,
    quant: 1,
    quantvend: 8,
    unit: "un",
    image: p24_img,
    price: 1350,
    parc: true,
    parc_quant: 12,
    price_unit: 1350,
    free_shipping: true,
    offer: true,
    porc_offer: 15,
    offer_price: 1147.5,
    old_price: 1350,
  },
  {
    id: 25,
    name: "Colchão Ortopédico com Espuma de Memória",
    desc: "Colchão com suporte ortopédico e memória de forma.",
    category: 1,
    category_name: "Colchões",
    rating: 5,
    quant: 1,
    quantvend: 14,
    unit: "un",
    image: p25_img,
    price: 1400,
    parc: true,
    parc_quant: 12,
    price_unit: 1400,
    free_shipping: true,
    offer: false,
    porc_offer: 0,
    offer_price: 0,
    old_price: 1400,
  },
  {
    id: 26,
    name: "Beliche Infantil com Desenhos Animados",
    desc: "Beliche decorado com temas de desenhos animados.",
    category: 2,
    category_name: "Beliches",
    rating: 4,
    quant: 1,
    quantvend: 7,
    unit: "un",
    image: p26_img,
    price: 980,
    parc: true,
    parc_quant: 10,
    price_unit: 980,
    free_shipping: true,
    offer: true,
    porc_offer: 10,
    offer_price: 882,
    old_price: 980,
  },
  {
    id: 27,
    name: "Colchão King Size com Tecnologia Gel",
    desc: "Colchão king size com tecnologia de resfriamento a gel.",
    category: 1,
    category_name: "Colchões",
    rating: 5,
    quant: 1,
    quantvend: 10,
    unit: "un",
    image: p27_img,
    price: 2000,
    parc: true,
    parc_quant: 12,
    price_unit: 2000,
    free_shipping: true,
    offer: true,
    porc_offer: 10,
    offer_price: 1800,
    old_price: 2000,
  },
  {
    id: 28,
    name: "Beliche com Cama Auxiliar",
    desc: "Beliche com uma cama auxiliar adicional embutida.",
    category: 2,
    category_name: "Beliches",
    rating: 4,
    quant: 1,
    quantvend: 14,
    unit: "un",
    image: p28_img,
    price: 1500,
    parc: true,
    parc_quant: 12,
    price_unit: 1500,
    free_shipping: false,
    offer: true,
    porc_offer: 15,
    offer_price: 1275,
    old_price: 1500,
  },
  {
    id: 29,
    name: "Colchão Ortopédico Solteiro com Reforço de Bordas",
    desc: "Colchão ortopédico com bordas reforçadas para maior durabilidade.",
    category: 1,
    category_name: "Colchões",
    rating: 4,
    quant: 1,
    quantvend: 11,
    unit: "un",
    image: p29_img,
    price: 600,
    parc: true,
    parc_quant: 8,
    price_unit: 600,
    free_shipping: true,
    offer: true,
    porc_offer: 10,
    offer_price: 540,
    old_price: 600,
  },
  {
    id: 30,
    name: "Beliche com Cortinas",
    desc: "Beliche com cortinas para maior privacidade.",
    category: 2,
    category_name: "Beliches",
    rating: 5,
    quant: 1,
    quantvend: 5,
    unit: "un",
    image: p30_img,
    price: 1200,
    parc: true,
    parc_quant: 10,
    price_unit: 1200,
    free_shipping: true,
    offer: true,
    porc_offer: 10,
    offer_price: 1080,
    old_price: 1200,
  },
  {
    id: 31,
    name: "Colchão Infantil Antialérgico",
    desc: "Colchão com tratamento antialérgico para crianças.",
    category: 1,
    category_name: "Colchões",
    rating: 4,
    quant: 1,
    quantvend: 9,
    unit: "un",
    image: p31_img,
    price: 450,
    parc: true,
    parc_quant: 6,
    price_unit: 450,
    free_shipping: false,
    offer: true,
    porc_offer: 10,
    offer_price: 405,
    old_price: 450,
  },
  {
    id: 32,
    name: "Beliche com Design Compacto",
    desc: "Beliche compacto ideal para ambientes pequenos.",
    category: 2,
    category_name: "Beliches",
    rating: 5,
    quant: 1,
    quantvend: 15,
    unit: "un",
    image: p32_img,
    price: 1350,
    parc: true,
    parc_quant: 12,
    price_unit: 1350,
    free_shipping: true,
    offer: true,
    porc_offer: 10,
    offer_price: 1215,
    old_price: 1350,
  },
  {
    id: 33,
    name: "Colchão de Espuma Densidade Alta",
    desc: "Colchão de espuma de alta densidade para maior suporte.",
    category: 1,
    category_name: "Colchões",
    rating: 4,
    quant: 1,
    quantvend: 20,
    unit: "un",
    image: p33_img,
    price: 800,
    parc: true,
    parc_quant: 10,
    price_unit: 800,
    free_shipping: false,
    offer: true,
    porc_offer: 15,
    offer_price: 680,
    old_price: 800,
  },
  {
    id: 34,
    name: "Beliche com Mesa de Estudo",
    desc: "Beliche com mesa de estudo embutida para otimizar o espaço.",
    category: 2,
    category_name: "Beliches",
    rating: 5,
    quant: 1,
    quantvend: 12,
    unit: "un",
    image: p34_img,
    price: 1600,
    parc: true,
    parc_quant: 12,
    price_unit: 1600,
    free_shipping: true,
    offer: true,
    porc_offer: 15,
    offer_price: 1360,
    old_price: 1600,
  },
  {
    id: 35,
    name: "Colchão King Ortopédico com Revestimento em Algodão",
    desc: "Colchão ortopédico king size com revestimento em algodão.",
    category: 1,
    category_name: "Colchões",
    rating: 5,
    quant: 1,
    quantvend: 18,
    unit: "un",
    image: p35_img,
    price: 2100,
    parc: true,
    parc_quant: 12,
    price_unit: 2100,
    free_shipping: true,
    offer: true,
    porc_offer: 10,
    offer_price: 1890,
    old_price: 2100,
  },
  {
    id: 36,
    name: "Beliche de Madeira Maciça",
    desc: "Beliche resistente feito em madeira maciça.",
    category: 2,
    category_name: "Beliches",
    rating: 4,
    quant: 1,
    quantvend: 6,
    unit: "un",
    image: p36_img,
    price: 1700,
    parc: true,
    parc_quant: 12,
    price_unit: 1700,
    free_shipping: true,
    offer: false,
    porc_offer: 0,
    offer_price: 0,
    old_price: 1700,
  },
];
export default all_products;
