export const notifications = [
  {
    id: 1,
    description: "Novo pedido realizado",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 2,
    description: "Produto foi entregue",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 3,
    description: "Promoção disponível",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 4,
    description: "Seu pagamento foi aprovado",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 5,
    description: "Novo comentário no produto",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 6,
    description: "Novo comentário no produto",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 6,
    description: "Novo comentário no produto",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 6,
    description: "Novo comentário no produto",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 6,
    description: "Novo comentário no produto",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 6,
    description: "Novo comentário no produto",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 6,
    description: "Novo comentário no produto",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
  {
    id: 6,
    description: "Novo comentário no produto",
    message: "Pedido #1234",
    imageUrl: "https://via.placeholder.com/150",
    date: "Há 5 minutos",
    pedido_id: 1234,
  },
];
